// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeBook.Data;

#nullable disable

namespace RecipeBook.Data.Migrations.Recipe
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20221030204700_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeBook.Data.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FullTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9f9e974-3da7-458c-a235-afc0e2e3ae8d"),
                            Category = 0,
                            FullTitle = "1 cup flour",
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7")
                        },
                        new
                        {
                            Id = new Guid("2d6e2d77-1209-4466-ab77-f9333b834127"),
                            Category = 5,
                            FullTitle = "2 eggs",
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7")
                        },
                        new
                        {
                            Id = new Guid("27ae292b-5e9e-46a2-b6a0-f3ecd3092490"),
                            Category = 10,
                            FullTitle = "1 1/4 cups milk",
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7")
                        },
                        new
                        {
                            Id = new Guid("38cadab8-9b22-45e7-a5bb-cc92511cb496"),
                            Category = 27,
                            FullTitle = "1 teaspoon sugar",
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7")
                        },
                        new
                        {
                            Id = new Guid("50570067-1919-42c0-b491-599be9777fd8"),
                            FullTitle = "A pinch of salt (tip of the teaspoon)",
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7")
                        },
                        new
                        {
                            Id = new Guid("356670d6-955b-461c-b5cb-7f0ab02e64a5"),
                            Category = 29,
                            FullTitle = "Oil for frying",
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7")
                        },
                        new
                        {
                            Id = new Guid("945ae8dd-e224-4611-87e9-bcc069ef5f23"),
                            Category = 16,
                            FullTitle = "4 apples",
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd")
                        },
                        new
                        {
                            Id = new Guid("af56e05b-6d4e-409a-81ae-ef68faede5b2"),
                            Category = 18,
                            FullTitle = "4 carrots",
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd")
                        },
                        new
                        {
                            Id = new Guid("c8406077-5d94-487d-97ab-f0eb82f38d28"),
                            Category = 11,
                            FullTitle = "2 tablespoons sour cream",
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd")
                        },
                        new
                        {
                            Id = new Guid("2284c4bb-77e7-4b96-856d-464436d0a60d"),
                            FullTitle = "2 teaspoons sugar (optional)",
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd")
                        },
                        new
                        {
                            Id = new Guid("bd6cc4a4-589d-44ad-bd91-3718fa4366b6"),
                            Category = 18,
                            FullTitle = "4 carrots, trimmed",
                            RecipeId = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8")
                        },
                        new
                        {
                            Id = new Guid("c4ff9018-5cb0-4087-9ddb-9189c772f9a9"),
                            Category = 16,
                            FullTitle = "2 apples, quartered",
                            RecipeId = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8")
                        },
                        new
                        {
                            Id = new Guid("47875b40-697e-4712-98d7-185a65c6846d"),
                            FullTitle = "2 stalks celery (optional)",
                            RecipeId = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8")
                        },
                        new
                        {
                            Id = new Guid("7daa1a94-a628-4bb0-9386-68c9eef52bc9"),
                            FullTitle = "1,5 cm piece of fresh ginger (optional)",
                            RecipeId = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8")
                        });
                });

            modelBuilder.Entity("RecipeBook.Data.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Category = 2,
                            Note = "I always pour on the pancake batter using a measuring cup, so I end up with consistently-sized pancakes.",
                            PictureTitle = "1",
                            Title = "Thin Pancakes"
                        },
                        new
                        {
                            Id = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd"),
                            Category = 0,
                            Note = "If you won't immediately consume the salad, spray it with a little bit of lemon juice and leave it in the fridge. Consume the same day though.",
                            PictureTitle = "2",
                            Title = "Apple and Carrot Salad"
                        },
                        new
                        {
                            Id = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8"),
                            Category = 4,
                            PictureTitle = "6",
                            Title = "Carrot and Apple Juice"
                        });
                });

            modelBuilder.Entity("RecipeBook.Data.Models.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46f6cc9f-d991-4d5f-8793-3c6dcdde3fca"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Sift the flour, sugar and salt, make a well in it."
                        },
                        new
                        {
                            Id = new Guid("de4f3533-957e-444a-908a-993c767cd9b5"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Crack in the eggs, add a bit of the milk."
                        },
                        new
                        {
                            Id = new Guid("74a3befc-0939-4bcd-bf19-7cbe5b8b50ee"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Then start whisking it all together (you can use a mixer)."
                        },
                        new
                        {
                            Id = new Guid("73c2b0b3-195e-405c-a653-ebf4c99fec43"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Next, whisk in the rest of the milk and until you have a pancake batter that resembles the consistency of whipping cream."
                        },
                        new
                        {
                            Id = new Guid("c8aa9118-429e-44f3-9bcb-6202600dc264"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Add on a bit of oil, and quickly swirl it around the pan. Make sure your pan is evenly nice and hot before you start cooking the pancakes. If the pan isn't hot enough, the recipe won't work."
                        },
                        new
                        {
                            Id = new Guid("ca008e8d-bf63-4b8a-8f49-16bcd852f1f6"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Then pour on the pancake batter and quickly swirl it around."
                        },
                        new
                        {
                            Id = new Guid("45db259b-24b8-41e1-8d23-860afc523dc7"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Cook until the batter is no longer liquid."
                        },
                        new
                        {
                            Id = new Guid("2facd95d-e737-4e0a-a6fc-b154b3f857a7"),
                            RecipeId = new Guid("c8e54483-9580-4e68-8f1a-b3da6c34f4b7"),
                            Text = "Serve with jam, sour cream, ice cream with berries and fruits - whatever you want!"
                        },
                        new
                        {
                            Id = new Guid("27bc1fc2-ed4d-4ab7-87ae-ce765d88f696"),
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd"),
                            Text = "Wash, peel and grate apples and carrots. Combine."
                        },
                        new
                        {
                            Id = new Guid("70f71220-b6fc-4552-be5a-3c489b3c83d2"),
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd"),
                            Text = "Add sugar and sour cream. Mix everything thoroughly so that the sugar melts to the maximum."
                        },
                        new
                        {
                            Id = new Guid("43f505fd-d2b0-4ff8-9510-448eaa611f5f"),
                            RecipeId = new Guid("f6d3eecc-c5d6-4daf-9fae-5e940e1f2cdd"),
                            Text = "Serve the delicious salad to the table."
                        },
                        new
                        {
                            Id = new Guid("64a13b87-72d2-498f-afe8-6e210513580c"),
                            RecipeId = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8"),
                            Text = "Run carrots, apples, (celery) through a juicer, alternating carrot, apple, and, optionally, celery, according to manufacturer's instructions."
                        },
                        new
                        {
                            Id = new Guid("302f0eb5-e1be-46dd-9f71-e4e16a5aa722"),
                            RecipeId = new Guid("ac0bd784-95de-4693-ad01-1553dd8606f8"),
                            Text = "Add ginger to juicer and process (optional)."
                        });
                });

            modelBuilder.Entity("RecipeBook.Data.Models.Ingredient", b =>
                {
                    b.HasOne("RecipeBook.Data.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeBook.Data.Models.Step", b =>
                {
                    b.HasOne("RecipeBook.Data.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeBook.Data.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
